// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbpEEZWyYbqTa_R_YC0tjWlcC1b_aBVv4',
    appId: '1:137178342437:web:b0e6a999fc2c51c7db0bcc',
    messagingSenderId: '137178342437',
    projectId: 'quiz-70e89',
    authDomain: 'quiz-70e89.firebaseapp.com',
    storageBucket: 'quiz-70e89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSnyPBhzqwS-pR93vPgShf_LJoquetN4',
    appId: '1:137178342437:android:dba37877e4aebcbbdb0bcc',
    messagingSenderId: '137178342437',
    projectId: 'quiz-70e89',
    storageBucket: 'quiz-70e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-VSt2sdw2h1o2YMLylrCqXIgBh-_eeZw',
    appId: '1:137178342437:ios:c1310bf3a7b1f971db0bcc',
    messagingSenderId: '137178342437',
    projectId: 'quiz-70e89',
    storageBucket: 'quiz-70e89.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-VSt2sdw2h1o2YMLylrCqXIgBh-_eeZw',
    appId: '1:137178342437:ios:c1310bf3a7b1f971db0bcc',
    messagingSenderId: '137178342437',
    projectId: 'quiz-70e89',
    storageBucket: 'quiz-70e89.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbpEEZWyYbqTa_R_YC0tjWlcC1b_aBVv4',
    appId: '1:137178342437:web:c4a5d1db1a3298c3db0bcc',
    messagingSenderId: '137178342437',
    projectId: 'quiz-70e89',
    authDomain: 'quiz-70e89.firebaseapp.com',
    storageBucket: 'quiz-70e89.firebasestorage.app',
  );
}
